version: '3.9'

services:
  seed:
    build:
      context: .
      dockerfile: docker/prod.Dockerfile
    container_name: seed
    env_file:
      - src/environment/.env.production
    ports:
      - "3000:80/tcp"
    volumes:
      - '/app/node_modules'
